name: babylon
description: "Babylon-Willian-Test"
version: 1.0.0+3
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  provider: ^6.1.5
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  collection: ^1.19.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  uuid: ^4.5.1
  meta: ^1.16.0
  flutter_localization: ^0.3.3
  package_info_plus: ^8.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/png/        
    # - .env
